local_library/catalog/urls.py
from django.urls import path
from catalog.views.book_instance import LoanedBooksByUserListView
from . import views


urlpatterns = [
    path('', views.index , name = 'index'),
    path('books/', views.BookListView.as_view(), name = 'books'),
    path('books/<int:pk>/', views.book_detail, name='book-detail'),
    path('books/create/', views.create_book, name='create-book'),
    path('authors/', views.AuthorsListView.as_view(), name = 'authors'),
    path('authors/create', views.create_author, name = 'create-author'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name = 'author-detail'),
    path('borrowed-books/', views.LoanedBooksByUserListView.as_view(), name = 'borrowed-books'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

local_library/local_library/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, reverse
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='catalog'), name='home'),
    path('admin/', admin.site.urls),
    path('catalog/' , include('catalog.urls')),
    path('accounts/' , include('accounts.urls'))

]

local_library/catalog/models.py
import uuid
from django.db import models
from datetime import date

# Create your models here.


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(verbose_name='Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
        db_table = 'author'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    
    def __str__(self):
        
        return self.first_name + ' ' + self.last_name

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    class Meta:
        db_table = 'genre'

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Book(models.Model):
    """Represents a Book"""
    title = models.CharField(max_length=200 , null = False, blank = False, help_text = 'Book')
    isbn = models.CharField(verbose_name = 'ISBN',max_length=13, unique=True, help_text = '13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    author = models.ManyToManyField(to = 'Author')
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book', null=True)
    genre = models.ManyToManyField(to='Genre', help_text='Select a genre for this book')

    class Meta:
        db_table = 'book'
        
    def __str__(self):
        """String for representing the Model object."""
        return self.title

class BookInstance(models.Model):
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )
    borrower = models.ForeignKey('accounts.CustomUser', on_delete = models.SET_NULL, null=True, blank =True)
    class Meta:
        ordering = ['due_back']

    @property
    def is_overdue(self):
        if self.due_back and self.status == 'o' and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

local_library/catalog/forms.py
from .models import Book
from django import forms
import datetime
from django.core.exceptions import ValidationError


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).",widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    def clean_renewal_date(self):
        cleaned_date = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if cleaned_date < datetime.date.today():
            raise ValidationError('Invalid date - renewal in past')

        # Check if a date is in the allowed range (+4 weeks from today).
        if cleaned_date > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError('Invalid date - renewal more than 4 weeks ahead')

        # Remember to always return the cleaned data.
        return cleaned_date


class BookModelForm(forms.ModelForm):

    class Meta:
        model = Book
        # fields = '__all__'
        fields = ('title', 'isbn', 'author', 'summary','genre')


class AuthorForm(forms.Form):

    first_name =forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

# Line 38 dhe 39 kam hequr para widget max_length=False

    date_of_birth = forms.DateField(required=False,widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_death = forms.DateField(required=False,widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    def clean_date_of_death(self):
        date_of_birth = self.cleaned_data['date_of_birth']
        date_of_death= self.cleaned_data['date_of_death']
        if date_of_death < date_of_birth:
            raise ValidationError('Date of death cannot be prior date of birth.')
        return date_of_death

local_library/catalog/views.py
from django.http.response import Http404, HttpResponse 
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre

# Create your views here.
from .models import Book, Author, BookInstance, Genre
from django.views import generic 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def index(request):
    """View function for home page of site."""
    num_visits = request.session.get('num_visits', 0)

    # Generate counts of some of the main objects
    request.session['num_visits'] = num_visits + 1
    num_books = Book.objects.all().count()
    print(Book.objects.all().count())
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


def hello(request):
    return HttpResponse('Hello!!!')

class BookListView(LoginRequiredMixin ,generic.ListView):
    model = Book
    context_object_name = 'book_list'
    template_name = "books.html"
    

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book_detail.html'

@login_required
def book_detail(request, pk):
    try:
        book = Book.objects.get(id=pk)
    except Book.DoesNotExist:
        raise Http404   
    return render(request, 'book_detail.html', context ={ 'book': book} )

class AuthorsListView(LoginRequiredMixin, generic.ListView):
    model = Author
    template_name = 'authors.html'

class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'

local_library/catalog/views/author.py
from django.shortcuts import redirect,  render
from catalog.forms import AuthorForm
from django.http.response import Http404, HttpResponse 
from django.shortcuts import render
from catalog.models import Book, Author, BookInstance, Genre

# Create your views here.
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class AuthorsListView(LoginRequiredMixin, generic.ListView):
    model = Author
    template_name = 'authors.html'

class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'

def create_author(request):
    if request.method == 'Post':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = Author.objects.create(
            first_name =form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            date_of_birth=form.cleaned_data['date_of_birth'],
            date_of_death=form.cleaned_data['date_of_death'],
            )
        return redirect('authors')

    else:
        form = AuthorForm()
        context = {'forms':form}
        return render (request,'create_author.html',context)

local_library/catalog/views/book.py
from django.http.response import Http404, HttpResponse 
from django.shortcuts import redirect, render
from catalog.forms import BookModelForm
from catalog.models import Book, Author, BookInstance, Genre

# Create your views here.
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class BookListView(LoginRequiredMixin ,generic.ListView):
    model = Book
    context_object_name = 'book_list'
    template_name = "books.html"

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book_detail.html'

@login_required
def book_detail(request, pk):
    try:
         book = Book.objects.get(id=pk)
    except Book.DoesNotExist:
        raise Http404   
    return render(request, 'book_detail.html', context ={ 'book': book} )


def create_book(request):
    if request.method == 'POST':
        form =BookModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('books')
    else:
        form = BookModelForm()
        context =  {'form':form}
        return render(request, 'create_book.html', context)

local_library/catalog/views/book_instance.py
from django.http.response import Http404, HttpResponse 
from django.shortcuts import render
from catalog.models import Book, Author, BookInstance, Genre

# Create your views here.
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name ='bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

import datetime

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalog.forms import RenewBookForm

def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

local_library/catalog/templates/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ author.first_name }}{{ author.last_name }}</h1>

  <p><strong>Date of Birth:{{author.date_of_birth }}</strong></p>
  <p><strong>Date of Death:{{author.date_of_death }}</strong></p>
  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Book Written</h4>
    {% if author.book_set.all %}
      {% for book in author.book_set.all %}
      <hr>
      <a href = "{% url 'book_detail' book.pk}"><strong>{{book.title}}</strong></a>
      <p><strong>{{ book.isbn}}</strong></p>
      {% endfor %}
    {% else %}
    <p><strong>The author has not writen any book.</strong></p>
    {% endif %}
    </div>
{% endblock %}

local_library/catalog/templates/authors.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>authors List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name}}{{ author.first_name}}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in the database.</p>
  {% endif %}
{% endblock %}

local_library/catalog/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Local Library</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item active  ">
                        <a class="nav-link" href="{% url 'borrowed-books' %}">Borrowed Books</a>
                    </li>
                    {% endif %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'books' %}">Books</a>
                    </li>
                    <li class="nav-item active  ">
                        <a class="nav-link" href="{% url 'authors' %}">Authors</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item active nav navbar-nav navbar-right ">
                        <a class="nav-link" href="/admin/">Admin</a>
                    </li>
                    <li class="nav-item active nav navbar-nav navbar-right ">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item active nav navbar-nav navbar-right ">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item active nav navbar-nav navbar-right ">
                        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                    </li>
                    {% endif %}


                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            
        </div>
    </nav>
    {% block content %}
    
    {% endblock %}
    

</body>

</html>

local_library/catalog/templates/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

local_library/catalog/templates/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

local_library/catalog/templates/books.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a> ({{book.author}}
        {% for author in book.authors.all %}
        <a href = "{% url 'author-detail' author.pk %}">{{author.first_name}} {{ author.last_name}}<a>
        {% endfor %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

local_library/catalog/templates/create_author.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>New author</h2>
  
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    </table>
    <input type="submit" value="Create">
  </form>
{% endblock %}

local_library/catalog/templates/create_book.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>New book</h2>
  
  <form action="" method="post">
    {% csrf_token %}
    
    {{ form.as_p }}
    </table>
    <input type="submit" value="Create">
  </form>
{% endblock %}

local_library/catalog/templates/index.html
{% extends "base_generic.html" %}
{% block title %}<title>Index Page</title>{% endblock %}
{% block content %}
{% if user.is_authenticated%}

  <h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul><p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
  {% else %}
  <div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Local Library <i class="fas fa-globe-americas"></i></h1>
        <p class="lead">This is a simple Local Library management platform, log in to get statrted!</p>
        <hr class="my-4">
        <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Log In</a>
    </div>
  </div>
  {% endif %}
{% endblock %}

local_library/catalog/templates/new_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Local Library</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item active  ">
                        <a class="nav-link" href="{% url 'borrowed-books' %}">Borrowed Books</a>
                    </li>
                    {% endif %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'books' %}">Books</a>
                    </li>
                    <li class="nav-item active  ">
                        <a class="nav-link" href="{% url 'authors' %}">Authors</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item active nav navbar-nav navbar-right ">
                        <a class="nav-link" href="/admin/">Admin</a>
                    </li>
                    <li class="nav-item active nav navbar-nav navbar-right ">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item active nav navbar-nav navbar-right ">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item active nav navbar-nav navbar-right ">
                        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                    </li>
                    {% endif %}


                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            
        </div>
    </nav>
    
    <div class="container">
      <div class="jumbotron">
          <h1 class="display-4">Local Library <i class="fas fa-globe-americas"></i></h1>
          <p class="lead">This is a simple Local Library management platform, log in to get statrted!</p>
          <hr class="my-4">
          <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Log In</a>
      </div>
    </div>

    <div class="container mt-4">
        <div class="row">
            <div class="col-6">
                <h2>Sign-in</h2>
                <form>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                            placeholder="Enter email">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                            else.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>

</body>

</html>